# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilePrimaryPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profilePic',
        ),
        migrations.RemoveField(
            model_name='profilephotos',
            name='user',
        ),
        migrations.AddField(
            model_name='profilephotos',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='socialMedia.profile', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileprimarypic',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialMedia.profile', unique=True),
        ),
        migrations.AddField(
            model_name='profileprimarypic',
            name='profilePic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='socialMedia.profilePhotos'),
        ),
    ]
