# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0004_auto_20160706_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='/static/socialmedia/images/')),
            ],
        ),
    ]
