# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0006_auto_20160707_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 7, 16, 51, 55, 472995, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
