# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialMedia', '0007_wallpost_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='postComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(blank=True, max_length=500)),
                ('commentSender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialMedia.wallPost')),
            ],
        ),
    ]
