# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0008_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='faceBookID',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
